baseURL: https://danielpaval.github.io/
languageCode: en-us
title: paval.io

params:
  defaultTheme: "light"
  showtoc: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowBreadCrumbs: true
  author: Daniel Paval
  homeInfoParams:
    Title: Welcome to my *headspace*!
    Content: Exploring technical topics with curiosity and sharing insights to help you get a head start.
  socialIcons:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/danielpaval/"
  search:
    enabled: true

markup:
  goldmark:
    renderHooks:
      image:
        enableDefault: true

module:
  mounts:
  - source: assets
    target: assets
  - source: static
    target: assets
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

ignoreLogs:
  - warning-goldmark-raw-html

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: "ðŸ”Žï¸Ž Search"
          url: search/
          weight: 10
        - name: "ðŸ—“ Calendar"
          url: archives/
          weight: 20        
        - name: "âµŒ Tags"
          url: tags/
          weight: 30
        